# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "docker"
    directory: "/"
    registries:
      dockerhub:
        type: docker-registry
        url: https://registry.hub.docker.com
      oracle:
        type: docker-registry
        url: https://container-registry.oracle.com
    reviewers:
      - "fniephaus"
    schedule:
      interval: "weekly"
